#docker-compose.yml   #author: zeh sobrinho & tutorC
#date: 10-03-24
#vesão: 1.0.1 

version: "3.5"

volumes:
  sqlite_data: {} 

services:

  api01:
    image: tutorC/rinha-backend-c-2024-q1:latest
    ports: 
      - "4000:4000"
    environment:
    - CONFIG_FILE=/app/config/api.conf
    volumes:   
      - sqlite_data:/app 
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"

  api02:
    image: tutorC/rinha-backend-c-2024-q1:latest
    ports:
      - "4001:4001" 
    environment:
      - PORT=4001        
      - POOL_SIZE=2
      - THREAD_POOL_SIZE=1    
      - CONNECTION_STRING=file:/app/banco.sqlite?cache=shared
    volumes:    
      - sqlite_data:/app
    deploy:  
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "9999:9999"
    deploy:  
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

networks:
  default: 
    driver: bridge
    name: rinha_backend_2024_q1

